//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void ACMP1_enter_DefaultMode_from_RESET(void);
extern void DAC0_enter_DefaultMode_from_RESET(void);
extern void BURTC_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void OPAMP0_enter_DefaultMode_from_RESET(void);
extern void OPAMP1_enter_DefaultMode_from_RESET(void);
extern void OPAMP2_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void USART2_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void LEUART1_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void I2C1_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void TIMER2_enter_DefaultMode_from_RESET(void);
extern void TIMER3_enter_DefaultMode_from_RESET(void);
extern void LETIMER0_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PCNT1_enter_DefaultMode_from_RESET(void);
extern void PCNT2_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void ETM_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define ADC0_CH7_PIN                    (7)
#define ADC0_CH7_PORT                   (gpioPortD)

#define CHG_STATUS_PIN                  (9)
#define CHG_STATUS_PORT                 (gpioPortC)

#define CTS_PIN                         (3)
#define CTS_PORT                        (gpioPortD)

#define GPIO_SWO_PIN                    (2)
#define GPIO_SWO_PORT                   (gpioPortF)

#define GSM_PWR_KEY_PIN                 (9)
#define GSM_PWR_KEY_PORT                (gpioPortA)

#define GSM_SLEEP_PIN                   (5)
#define GSM_SLEEP_PORT                  (gpioPortD)

#define GSM_VDD_SENS_PIN                (10)
#define GSM_VDD_SENS_PORT               (gpioPortA)

#define HFXO_N_PIN                      (14)
#define HFXO_N_PORT                     (gpioPortB)

#define HFXO_P_PIN                      (13)
#define HFXO_P_PORT                     (gpioPortB)

#define I2C0_SCL_PIN                    (1)
#define I2C0_SCL_PORT                   (gpioPortA)

#define I2C0_SDA_PIN                    (0)
#define I2C0_SDA_PORT                   (gpioPortA)

#define LFXO_N_PIN                      (8)
#define LFXO_N_PORT                     (gpioPortB)

#define LFXO_P_PIN                      (7)
#define LFXO_P_PORT                     (gpioPortB)

#define MMA_INT1_PIN                    (2)
#define MMA_INT1_PORT                   (gpioPortA)

#define MMA_INT2_PIN                    (3)
#define MMA_INT2_PORT                   (gpioPortA)

#define PGOOD_PIN                       (10)
#define PGOOD_PORT                      (gpioPortC)

#define RING_PIN                        (2)
#define RING_PORT                       (gpioPortD)

#define RTS_PIN                         (4)
#define RTS_PORT                        (gpioPortD)

#define STATUS_LED_PIN                  (6)
#define STATUS_LED_PORT                 (gpioPortD)

#define TERMINATION_DISABLE_PIN         (8)
#define TERMINATION_DISABLE_PORT        (gpioPortC)

#define USART0_CLK_PIN                  (12)
#define USART0_CLK_PORT                 (gpioPortE)

#define USART0_CS_PIN                   (13)
#define USART0_CS_PORT                  (gpioPortE)

#define USART0_RX_PIN                   (11)
#define USART0_RX_PORT                  (gpioPortE)

#define USART0_TX_PIN                   (10)
#define USART0_TX_PORT                  (gpioPortE)

#define USART1_RX_PIN                   (1)
#define USART1_RX_PORT                  (gpioPortD)

#define USART1_TX_PIN                   (0)
#define USART1_TX_PORT                  (gpioPortD)

#define USB_DM_PIN                      (10)
#define USB_DM_PORT                     (gpioPortF)

#define USB_DP_PIN                      (11)
#define USB_DP_PORT                     (gpioPortF)

#define V_GNSS_EN_PIN                   (8)
#define V_GNSS_EN_PORT                  (gpioPortA)

#define V_GSM_EN_PIN                    (11)
#define V_GSM_EN_PORT                   (gpioPortB)

// [User-defined pin name abstraction]$

#endif

